/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N5nmaMzeqlK
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import Image from "next/image";
import { Card } from "@/components/ui/card";

export function AiService() {
  return (
    <section>

        <div id="launch-service" className="py-20 mx-auto grid grid-cols-1 md:grid-cols-10 md:w-5/6">

          <div className="w-full md:col-span-7">
            <div className="grid grid-cols-2 md:grid-cols-6 gap-8 p-8">
              <Card className="h-full col-span-3 rounded-3xl shadow-2xl overflow-hidden bg-transparent">
                <div className="relative aspect-square">
                  <Button variant="ghost" className="font-thin p-6 text-xs absolute right-0 text-slate-300">ID 967890</Button>
                  <Image
                    alt="Image"
                    className="object-cover"
                    src="/1.png"
                    width= "480"
                    height= "507"
                    style={{
                      objectFit: "cover",
                    }}
                  />
                  <div className="text-slate-400 absolute m-5  bg-stone-600 bottom-0  flex flex-col items-center justify-center gap-2 p-6">
                    <p>Improve your business appearance.</p>
                  </div>
                </div>
              </Card>
              <Card className="h-full rounded-3xl shadow-2xl overflow-hidden bg-transparent">
                <div className="relative aspect-square">
                  <Button variant="ghost" className="font-thin p-6 text-xs absolute right-0 text-slate-300">ID 967890</Button>
                  <Image
                    alt="Image"
                    className="object-cover"
                    src="/2.png"
                    width= "430"
                    height= "280"
                    style={{
                      objectFit: "cover",
                    }}
                  />
                  <div className="text-slate-400 absolute bottom-0  flex flex-col items-center justify-center gap-2 p-6">
                    <p>Gain confidence</p>
                  </div>
                </div>
              </Card>
              <Card className="h-full rounded-3xl shadow-2xl overflow-hidden bg-transparent">
                <div className="relative aspect-square">
                  <Button variant="ghost" className="font-thin p-6 text-xs absolute right-0 text-slate-300">ID 967890</Button>
                  <Image
                    alt="Image"
                    className="object-cover"
                    src="/3.png"
                    width= "430"
                    height= "280"
                    style={{
                      objectFit: "cover",
                    }}
                  />
                  <div className="text-slate-400 absolute bottom-0  flex flex-col items-center justify-center gap-2 p-6">
                    <p>Look at yourself differently than before</p>
                  </div>
                </div>
              </Card>
              <Card className="h-full rounded-3xl shadow-2xl overflow-hidden bg-transparent">
                <div className="relative aspect-square">
                  <Button variant="ghost" className="font-thin p-6 text-xs absolute right-0 text-slate-300">ID 967890</Button>
                  <Image
                    alt="Image"
                    className="object-cover"
                    src="/4.png"
                    width= "430"
                    height= "280"
                    style={{
                      objectFit: "cover",
                    }}
                  />
                  <div className="text-slate-400 absolute bottom-0  flex flex-col items-center justify-center gap-2 p-6">
                    <p>Boost your Tinder profile</p>
                  </div>
                </div>
              </Card>
              <Card className="h-full rounded-3xl shadow-2xl overflow-hidden bg-transparent">
                <div className="relative aspect-square">
                  <Button variant="ghost" className="font-thin p-6 text-xs absolute right-0 text-slate-300">ID 967890</Button>
                  <Image
                    alt="Image"
                    className="object-cover"
                    src="/5.png"
                    width= "430"
                    height= "280"
                    style={{
                      objectFit: "cover",
                    }}
                  />
                  <div className="text-slate-400 absolute bottom-0  flex flex-col items-center justify-center gap-2 p-6">
                    <p>And for fun!</p>
                  </div>
                </div>
              </Card>
            </div>
          </div>

          <div className="w-full md:col-span-3 md:order-last text-start p-12 border border-slate-200 rounded-3xl shadow-2xl bg-gradient-to-tl from-stone-900 to-stone-700">
            <Badge>Coming soon</Badge>
            <h1 className="text-slate-200 text-6xl font-extrabold">hellllo</h1>
          </div>

        </div>

        <div className="flex flex-row py-20 md:w-5/6 mx-auto">
          <div className="basis-full md:basis-5/12 p-6">
            <h1 className="md:text-end pb-2 animate-fade-up bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text text-center  font-extrabold tracking-tighter text-transparent drop-shadow-sm [text-wrap:balance] text-5xl md:text-8xl md:leading-[5rem]">
            Use Cases
            </h1>
          </div>
          <div className="basis-full md:basis-7/12 p-6">
            <p className="text-start mx-auto max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
            We are developers. We often don't see what our development will be used for. We only know, this is the most exciting project we have worked on, with a lot of potential.
            If you have a dream too, feel free contact us: utopia@utopia.express
            </p>
          </div>
        </div> 

    </section>
  )
}



