/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3E3dlWMavIx
 */
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Link from "next/link";
import { buttonVariants } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { badgeVariants } from "@/components/ui/badge";
import Image from "next/image";

export function BentoCards() {
  return (
    <div className="w-3/4 mx-auto">
      <div className="flex flex-row items-center space-x-4 justify-self-center">

        <div className="basis-1/3 p-5">
          <p className="text-lg font-normal text-slate-500 text-end">Meet your photogenic</p>
          <h1 className="pb-4  bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text text-end text-8xl font-extrabold tracking-tighter text-transparent">Clone</h1>
          <div className="flex flex-row">
            <Card className=" h-full shadow-2xl rounded-3xl overflow-hidden bg-sky-100	">
              <div className="relative">
                <Image
                  alt="Image"
                  className="object-cover"
                  src="girl2.png"
                  style={{
                    objectFit: "cover",
                  }}
                />
              </div>
            </Card>
            <Card className=" h-full shadow-2xl rounded-3xl overflow-hidden bg-sky-100	">
              <div className="relative">
                <Image
                  alt="Image"
                  className="object-cover"
                  src="girls.png"
                  style={{
                    objectFit: "cover",
                  }}
                />
              </div>
            </Card>
          </div>

        </div>

        <div className="basis-1/3">
          <Card className="h-full rounded-3xl shadow-2xl overflow-hidden bg-transparent">
            <div className="relative aspect-square">
              
              <Button variant="ghost" className="font-thin p-6 text-xs absolute right-0 text-slate-300">ID 967890</Button>
              <Image
                alt="Image"
                className="object-cover"
                src="/boy1.png"
                style={{
                  objectFit: "cover",
                }}
              />
              <div className="absolute bottom-0  flex flex-col items-center justify-center gap-2 p-6">

              </div>
            </div>
          </Card>
        </div>

        <div className="basis-1/3 p-5">
          <h1 className="pb-4 bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text text-end text-8xl font-extrabold tracking-tighter text-transparent">21<span>€</span></h1>
      
          <div className="space-y-1">
            <p className="text-sm text-slate-400">
            50 step training process + Highest quality
            </p>
          </div>

      <Separator className="my-3" />
      <div className="flex h-5 space-x-3 text-sm text-slate-400">
        <div className="font-bold ">1 Credit</div>
        <Separator orientation="vertical" />
        <div>1 Model ID</div>
        <Separator orientation="vertical" />
        <div>12 photos</div>
        <Separator orientation="vertical" />
        <div className="text-end">21 eur</div>
      </div>
      <Separator className="my-3" />
      <div className="flex h-5 space-x-3 text-sm text-slate-400">
        <div className="font-bold ">3 Credit</div>
        <Separator orientation="vertical" />
        <div>3 Model ID</div>
        <Separator orientation="vertical" />
        <div>36 photos</div>
        <Separator orientation="vertical" />
        <div className="text-end">60 eur</div>
      </div>
      <Separator className="my-3" />
      <div className="flex h-5 space-x-3 text-sm text-slate-400">
        <div className="font-bold ">5 Credit</div>
        <Separator orientation="vertical" />
        <div>5 Model ID</div>
        <Separator orientation="vertical" />
        <div>60 photos</div>
        <Separator orientation="vertical" />
        <div className="text-end">95 eur</div>
      </div>
      <Separator className="my-3" />

              <Button className="justify-items-stretch mt-4 w-full transition-all	tracking-wide text-sm font-normal bg-transparent hover:bg-slate-200 text-slate-500 shadow-xl shadow-slate-500/20 hover:shadow-xl hover:shadow-slate-500/40 rounded-full dark:border-gray-900" asChild>
                <Link href="#">
                  <Avatar>
                    <AvatarImage src="https://i.postimg.cc/nrR0Kd8R/girl-icon.png" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                  <span className="transition-all mr-3 text-slate-500 hover:text-slate-400"></span>
                  Get your potraits <Badge variant="default">Badge</Badge>
                </Link>
              </Button>

        </div>







      </div>
    </div>
  )
}


function ImageIcon(props) {
  return (
  <svg  {...props} width="16" height="16" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-5 h-5">
    <path strokeLinecap="round" strokeLinejoin="round" d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
  </svg>
  
  )
}


