/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3E3dlWMavIx
 */
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { badgeVariants } from "@/components/ui/badge";
import Image from "next/image";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card";
import { Separator } from "@/components/ui/separator";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";



export function BentoCardsV4() {
  return (
    <div className="mx-auto md:w-2/3">
      <div className="grid md:grid-cols-11 items-center gap-6">

        <div className="col-span-5 ">
            <Card className="mb-6 h-full shadow-2xl rounded-3xl overflow-hidden bg-sky-100	">
              <div className="transition-all relative bg-gradient-to-br from-pink-100 to-slate-200 hover:from-slate-100 hover:to-fuchsia-100">
                <Image
                  alt="Image"
                  className="transition-all cover saturate-100  shadow-lg"
                  src="/lucybig2.png"
                  width= "1053"
                  height= "598"
                  style={{
                    objectFit: "cover",
                  }}
                />
                <div className="text-stone-600 absolute w-2/3 pl-8 pr-4 top-10 right-2 gap-2 text-right">
                    <p className="text-sm text-left">Leave the boring stuff for Lucy, your</p>
                    <h1 className="text-2xl leading-tight text-left">Personal Assistant</h1>
                    <p className="text-xs pl-3 pt-4 text-left text-stone-500"><EmailIcon/>Able to answer your emails</p>
                    <p className="text-xs pl-3 pt-1 text-left text-stone-500"><LearnIcon/>Able to learn & adapt</p>
                    <p className="text-xs pl-3 pt-1 pb-4 text-left text-stone-500"><HeartIcon/>Customizable personality</p>
                    <Link href="/" className="text-right">
                        <Button className="button-default shadow-lg shadow-stone-500/50">Get Early Access</Button>
                    </Link>
                </div>
              </div>
            </Card>

            <Card className="float-right w-2/3 h-full shadow-2xl rounded-3xl overflow-hidden bg-sky-100	">
              <div className="transition-all relative bg-gradient-to-br from-slate-100 to-slate-200 hover:from-slate-100 hover:to-fuchsia-100">
                <Image
                  alt="Image"
                  className="transition-all cover saturate-100 rounded-full shadow-lg"
                  src="/lucybig2.png"
                  width= "1053"
                  height= "787"
                  style={{
                    objectFit: "cover",
                  }}
                />
                <div className="text-stone-600 absolute w-2/3 pl-9 pr-4 top-10 right-2 gap-2 text-right">
                    <p className="text-sm text-right">Leave the boring stuff for</p>
                    <h1 className="text-4xl font-extrabold text-right">Lucy</h1>
                    <p className="text-xs pl-1 pt-4 text-left text-stone-500"><EmailIcon/>Able to answer your emails</p>
                    <p className="text-xs pl-1 pt-1 text-left text-stone-500"><LearnIcon/>Able to learn & adapt</p>
                    <p className="text-xs pl-1 pt-1 pb-4 text-left text-stone-500"><HeartIcon/>Customizable personality</p>
                    <Link href="/" className="text-right">
                        <Button className="button-default shadow-lg shadow-stone-500/50">Early Access</Button>
                    </Link>
                </div>
              </div>
            </Card>
        </div>

        <div className="col-span-4">
          <Card className="h-full rounded-3xl shadow-2xl overflow-hidden bg-stone-900">
            <div className="relative aspect-square">

              <HoverCard>
                <HoverCardTrigger className="absolute right-5 bottom-5">
                  <ImageInfoIcon/>
                </HoverCardTrigger>
                <HoverCardContent className="rounded-2xl shadow-2xl border-0 bg-stone-900">
                  <Image
                  alt="Image"
                  className="object-cover rounded-2xl"
                  src="/kiskep.png"
                  width= "285"
                  height= "100"
                  style={{
                    objectFit: "cover",
                  }}
                  />
                </HoverCardContent>
              </HoverCard>

              <p className="opacity-25 font-thin p-6 text-xs absolute right-8 bottom-0 text-slate-300">ID 967890</p>
              
              <Image
                alt="Image"
                className="object-cover"
                src="/boy1.png"
                width= "430"
                height= "280"
                style={{
                  objectFit: "cover",
                }}
              />
              <div className="text-slate-600 absolute bottom-8  gap-2 p-6">
                <h1 className="text-2xl text-left">One of those developers</h1>
                <p className="text-xs"> who haven't slept much in the last year and a half.</p>
              </div>
            </div>
          </Card>
        </div>

        <div className="col-span-2">
          <h1 className="bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text text-5xl md:text-8xl font-extrabold tracking-tighter text-transparent">21<span className="text-6xl">€</span><EurIcon/></h1>
            <Card className="float-right w-full h-full shadow-2xl rounded-3xl overflow-hidden bg-sky-100	">
              <div className="transition-all relative bg-gradient-to-br from-slate-100 to-slate-200 hover:from-slate-100 hover:to-fuchsia-100">
                <Image
                  alt="Image"
                  className="transition-all cover saturate-100 rounded-full shadow-lg"
                  src="/vanda1.png"
                  width= "1053"
                  height= "787"
                  style={{
                    objectFit: "cover",
                  }}
                />
                <div className="text-stone-600 absolute w-2/3 pl-9 pr-4 top-10 right-2 gap-2 text-right">
                    <p className="text-sm text-right">Leave the boring stuff for</p>
                    <h1 className="text-4xl font-extrabold text-right">Lucy</h1>
                    <p className="text-xs pl-1 pt-4 text-left text-stone-500"><EmailIcon/>Able to answer your emails</p>
                    <p className="text-xs pl-1 pt-1 text-left text-stone-500"><LearnIcon/>Able to learn & adapt</p>
                    <p className="text-xs pl-1 pt-1 pb-4 text-left text-stone-500"><HeartIcon/>Customizable personality</p>
                    <Link href="/" className="text-right">
                        <Button className="button-default shadow-lg shadow-stone-500/50">Early Access</Button>
                    </Link>
                </div>
              </div>
            </Card>
        </div>


      </div>
    </div>
  )
}


function ImageInfoIcon() {
  return (
<svg width="28" height="28" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="stroke-slate-600 hover:stroke-fuchsia-400">
  <path d="M6 3a3 3 0 0 0-3 3v1.5a.75.75 0 0 0 1.5 0V6A1.5 1.5 0 0 1 6 4.5h1.5a.75.75 0 0 0 0-1.5H6ZM16.5 3a.75.75 0 0 0 0 1.5H18A1.5 1.5 0 0 1 19.5 6v1.5a.75.75 0 0 0 1.5 0V6a3 3 0 0 0-3-3h-1.5ZM12 8.25a3.75 3.75 0 1 0 0 7.5 3.75 3.75 0 0 0 0-7.5ZM4.5 16.5a.75.75 0 0 0-1.5 0V18a3 3 0 0 0 3 3h1.5a.75.75 0 0 0 0-1.5H6A1.5 1.5 0 0 1 4.5 18v-1.5ZM21 16.5a.75.75 0 0 0-1.5 0V18a1.5 1.5 0 0 1-1.5 1.5h-1.5a.75.75 0 0 0 0 1.5H18a3 3 0 0 0 3-3v-1.5Z" />
</svg>
  )
}
function EurIcon() {
  return (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-4 h-4">
    <path strokeLinecap="round" strokeLinejoin="round" d="M14.25 7.756a4.5 4.5 0 1 0 0 8.488M7.5 10.5h5.25m-5.25 3h5.25M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg>
  )
}

function EmailIcon() {
    return (
<svg className="float-start w-4 h-4  mr-1" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
  <path className="stroke-stone-500" strokeLinecap="round" strokeLinejoin="round" d="M16.5 12a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0Zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 1 0-2.636 6.364M16.5 12V8.25" />
</svg>
    )
}


function LearnIcon() {
    return (
<svg className="float-start w-4 h-4 mr-1" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.75432 1.81954C7.59742 1.72682 7.4025 1.72682 7.24559 1.81954L1.74559 5.06954C1.59336 5.15949 1.49996 5.32317 1.49996 5.5C1.49996 5.67683 1.59336 5.84051 1.74559 5.93046L7.24559 9.18046C7.4025 9.27318 7.59742 9.27318 7.75432 9.18046L13.2543 5.93046C13.4066 5.84051 13.5 5.67683 13.5 5.5C13.5 5.32317 13.4066 5.15949 13.2543 5.06954L7.75432 1.81954ZM7.49996 8.16923L2.9828 5.5L7.49996 2.83077L12.0171 5.5L7.49996 8.16923ZM2.25432 8.31954C2.01658 8.17906 1.70998 8.2579 1.56949 8.49564C1.42901 8.73337 1.50785 9.03998 1.74559 9.18046L7.24559 12.4305C7.4025 12.5232 7.59742 12.5232 7.75432 12.4305L13.2543 9.18046C13.4921 9.03998 13.5709 8.73337 13.4304 8.49564C13.2899 8.2579 12.9833 8.17906 12.7456 8.31954L7.49996 11.4192L2.25432 8.31954Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>

    )
}

function HeartIcon() {
    return (
<svg className="float-start w-4 h-4 mr-1" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4.89346 2.35248C3.49195 2.35248 2.35248 3.49359 2.35248 4.90532C2.35248 6.38164 3.20954 7.9168 4.37255 9.33522C5.39396 10.581 6.59464 11.6702 7.50002 12.4778C8.4054 11.6702 9.60608 10.581 10.6275 9.33522C11.7905 7.9168 12.6476 6.38164 12.6476 4.90532C12.6476 3.49359 11.5081 2.35248 10.1066 2.35248C9.27059 2.35248 8.81894 2.64323 8.5397 2.95843C8.27877 3.25295 8.14623 3.58566 8.02501 3.88993C8.00391 3.9429 7.98315 3.99501 7.96211 4.04591C7.88482 4.23294 7.7024 4.35494 7.50002 4.35494C7.29765 4.35494 7.11523 4.23295 7.03793 4.04592C7.01689 3.99501 6.99612 3.94289 6.97502 3.8899C6.8538 3.58564 6.72126 3.25294 6.46034 2.95843C6.18109 2.64323 5.72945 2.35248 4.89346 2.35248ZM1.35248 4.90532C1.35248 2.94498 2.936 1.35248 4.89346 1.35248C6.0084 1.35248 6.73504 1.76049 7.20884 2.2953C7.32062 2.42147 7.41686 2.55382 7.50002 2.68545C7.58318 2.55382 7.67941 2.42147 7.79119 2.2953C8.265 1.76049 8.99164 1.35248 10.1066 1.35248C12.064 1.35248 13.6476 2.94498 13.6476 4.90532C13.6476 6.74041 12.6013 8.50508 11.4008 9.96927C10.2636 11.3562 8.92194 12.5508 8.00601 13.3664C7.94645 13.4194 7.88869 13.4709 7.83291 13.5206C7.64324 13.6899 7.3568 13.6899 7.16713 13.5206C7.11135 13.4709 7.05359 13.4194 6.99403 13.3664C6.0781 12.5508 4.73641 11.3562 3.59926 9.96927C2.39872 8.50508 1.35248 6.74041 1.35248 4.90532Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>

    )
}




