/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3E3dlWMavIx
 */
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { badgeVariants } from "@/components/ui/badge";
import Image from "next/image";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Video } from "../ui/video";



export function BentoCardsV2Video() {
  return (
    <div className="mx-auto sm:w-full md:w-5/6">
      <div className="grid grid-cols-1 md:grid-cols-3 items-center  justify-self-center">

        <div className="p-4 relative">

            <div className="h-36 relative">
              <span className="text-right text-slate-500 text-3xl tracking-tighter absolute right-0 top-0">Meet your<br />photogenic</span>
              <h1 className="absolute right-0 bottom-0 bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text sm:text-start md:text-end text-5xl md:text-8xl font-extrabold tracking-tighter text-transparent">Clone</h1>
            </div>
        </div>

        <div className="p-4">
          <Card className="m-8 h-full rounded-3xl border border-slate-300 shadow-xl shadow-slate-900/30 overflow-hidden bg-transparent">
            <div className="relative aspect-square">

              <p className="opacity-25 font-thin p-6 text-xs absolute right-2 bottom-0 text-slate-300">ID 967890</p>
              
                <Video/>
              <div className="text-slate-400 absolute bottom-8  flex flex-col items-center justify-center gap-2 p-6">
             
              </div>
            </div>
          </Card>
        </div>

        <div className="p-4">

          <p className="text-lg font-normal text-slate-500 text-start">Our AI-based service able to "learn" your unique characteristics and create fully realistic images of you.</p>

            <div className="flex flex-column gap-1">
                <div className="py-4 h-14 w-12 text-slate-400 relative">
                    <span className="absolute text-2xl italic text-right top-5 text-slate-500 right-0">from</span>
                </div>
                <div className="text-right">
                    <h1 className="bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text text-5xl md:text-8xl font-extrabold tracking-tighter text-transparent">21<span className="text-6xl">€</span><EurIcon/></h1>
                </div>
            </div>
            

            <Button className="border border-slate-200 bg-transparent hover:bg-transparent h-14 w-100 justify-items-stretch mt-3 transition-all tracking-wide text-sm font-normal text-slate-300 shadow-xl shadow-stone-700/10 hover:shadow-xl hover:shadow-stone-700/20 rounded-full" asChild>
                <div>

                    <Image
                        alt="Image"
                        className="object-cover rounded-full mr-2 shadow-md"
                        src="/01.png"
                        width= "34"
                        height= "34"
                        style={{
                        objectFit: "cover",
                       }}
                    />
                    <Image
                        alt="Image"
                        className="object-cover rounded-full mr-2 shadow-md"
                        src="/02.png"
                        width= "34"
                        height= "34"
                        style={{
                        objectFit: "cover",
                       }}
                    />
                    <Image
                        alt="Image"
                        className="object-cover rounded-full mr-2 shadow-md"
                        src="/04.png"
                        width= "34"
                        height= "34"
                        style={{
                        objectFit: "cover",
                       }}
                    />


                  <Dialog>
                        <DialogTrigger>
                          <Badge variant="secondary" className="pl-4 pr-4 pt-2 pb-2 pulse">
                          Create you Clone
                          </Badge>
                        </DialogTrigger>
                        <DialogContent className="rounded-xl">
                          <DialogHeader>
                            <DialogTitle className="pb-9 text-slate-500">Please select your type</DialogTitle>
                            <DialogDescription>
                              <div className="flex flex-row gap-9 justify-center pb-6">
                                <div>
                                  <Link href="https://clonegirls.utopia.express/login">
                                    <Image
                                        alt="Image"
                                        className="object-cover rounded-xl shadow-xl shadow-slate-600/50 saturate-0 hover:saturate-100"
                                        src="/select-woman.png"
                                        width= "122"
                                        height= "167"
                                        style={{
                                          objectFit: "cover",
                                        }}
                                    />
                                  </Link>
                                </div>
                                <div>
                                  <Link href="https://clone.utopia.express/login">
                                    <Image
                                        alt="Image"
                                        className="object-cover rounded-xl shadow-xl shadow-slate-600/50 saturate-0 hover:saturate-100"
                                        src="/select-man.png"
                                        width= "122"
                                        height= "167"
                                        style={{
                                          objectFit: "cover",
                                        }}
                                    />
                                  </Link>
                                </div>
                              </div>
                            </DialogDescription>
                          </DialogHeader>
                        </DialogContent>
                  </Dialog>
                </div>
            </Button> 

        </div>

      </div>



    </div>
  )
}


function OkIcon() {
  return (
<svg className="float-left mr-1 pt-1 stroke-fuchsia-200" width="13" height="13" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.49985 0.877045C3.84216 0.877045 0.877014 3.84219 0.877014 7.49988C0.877014 11.1575 3.84216 14.1227 7.49985 14.1227C11.1575 14.1227 14.1227 11.1575 14.1227 7.49988C14.1227 3.84219 11.1575 0.877045 7.49985 0.877045ZM1.82701 7.49988C1.82701 4.36686 4.36683 1.82704 7.49985 1.82704C10.6328 1.82704 13.1727 4.36686 13.1727 7.49988C13.1727 10.6329 10.6328 13.1727 7.49985 13.1727C4.36683 13.1727 1.82701 10.6329 1.82701 7.49988ZM7.49999 9.49999C8.60456 9.49999 9.49999 8.60456 9.49999 7.49999C9.49999 6.39542 8.60456 5.49999 7.49999 5.49999C6.39542 5.49999 5.49999 6.39542 5.49999 7.49999C5.49999 8.60456 6.39542 9.49999 7.49999 9.49999Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
  )
}
function EurIcon() {
  return (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-4 h-4">
    <path strokeLinecap="round" strokeLinejoin="round" d="M14.25 7.756a4.5 4.5 0 1 0 0 8.488M7.5 10.5h5.25m-5.25 3h5.25M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg>
  )
}


function CopyIcon() {
  return (
<svg className="float-right w-5 h-5 stroke-slate-200" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
  <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 7.5V6.108c0-1.135.845-2.098 1.976-2.192.373-.03.748-.057 1.123-.08M15.75 18H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08M15.75 18.75v-1.875a3.375 3.375 0 0 0-3.375-3.375h-1.5a1.125 1.125 0 0 1-1.125-1.125v-1.5A3.375 3.375 0 0 0 6.375 7.5H5.25m11.9-3.664A2.251 2.251 0 0 0 15 2.25h-1.5a2.251 2.251 0 0 0-2.15 1.586m5.8 0c.065.21.1.433.1.664v.75h-6V4.5c0-.231.035-.454.1-.664M6.75 7.5H4.875c-.621 0-1.125.504-1.125 1.125v12c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V16.5a9 9 0 0 0-9-9Z" />
</svg>

  )
}









