/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7r3IHOOfBNk
 */
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import { Badge } from "@/components/ui/badge";



export function CarouselSection() {
  return (
    <div className="w-full">
        <div className="grid items-center gap-0 lg:grid-cols-2">
          <div className="md:pr-16 md:border-r-2 md:border-slate-300">
            <div className="pt-44 pb-44">
              <p className="text-end"><Badge>Coming soon</Badge></p>
              <h1 className="md:text-end pb-4 animate-fade-up bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text font-extrabold tracking-tighter text-transparent drop-shadow-sm [text-wrap:balance] text-5xl md:text-7xl md:leading-[5rem]">
                Bring to life your Clone
              </h1>
              <p className="md:text-end text-gray-500 md:text-xl dark:text-gray-400">
                The best place to deploy your frontend. Instantly preview sites. Automate your build process. Integrate
                with GitHub.
              </p>
            </div>
          </div>
          <div className="max-h-64 flex items-center md:pl-16 md:pt-44 md:pb-44 hover:cursor-e-resize">
            <Carousel>
              <CarouselContent>
                <CarouselItem className="basis-1/3">
                  <img
                    alt="Image"
                    className="w-100 shadow-xl md:w-32 lg:w-48 aspect-[9/16] overflow-hidden rounded-3xl object-cover object-center"
                    height="1200"
                    src="/c1.png"
                    width="770"
                  />
                </CarouselItem>
                <CarouselItem className="basis-1/3">
                  <img
                    alt="Image"
                    className="w-100 shadow-xl md:w-32 lg:w-48 aspect-[9/16] overflow-hidden rounded-3xl object-cover object-center"
                    height="1200"
                    src="/c2.png"
                    width="960"
                  />
                </CarouselItem>
                <CarouselItem className="basis-1/2">
                  <img
                    alt="Image"
                    className="w-100 shadow-xl md:w-32 lg:w-48 aspect-[9/16] overflow-hidden rounded-3xl object-cover object-center"
                    height="1200"
                    src="/c3.png"
                    width="770"
                  />
                </CarouselItem>
              </CarouselContent>
              <CarouselPrevious />
              <CarouselNext />
            </Carousel>
          </div>
        </div>
    </div>
  )
}
