/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zQxAnDf2pf5
 */
import { CardContent, Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function ContactCard() {
  return (
    <div className="flex flex-row gap-9 justify-center pb-6">
    <Card className="w-full max-w-sm mx-auto rounded-2xl shadow-xl shadow-stone-950/90">
      <div className="p-4 flex items-center gap-4">
        <img
          alt="Avatar"
          className="rounded-full"
          height="64"
          src="/tamas.png"
          style={{
            aspectRatio: "64/64",
            objectFit: "cover",
          }}
          width="64"
        />
        <div className="grid gap-1.5">
          <div>
            <h3 className="text-lg font-bold">Tamas Konto</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Fonder, CTO</p>
          </div>
        </div>
      </div>
      <div className="border-t border-gray-200 dark:border-gray-800" />
      <CardContent className="p-4">
        <dl className="grid gap-2 text-sm">
          <div className="flex">
            <dt className="w-1/3 text-slate-400">Twitter</dt>
            <dd className="text-right ml-auto">@KontoTamas</dd>
          </div>
          <div className="flex">
            <dt className="w-1/3 text-slate-400">Email</dt>
            <dd className="text-right ml-auto">tamas@utopia.express</dd>
          </div>
        </dl>
      </CardContent>
    </Card>

    <Card className="w-full max-w-sm mx-auto rounded-2xl shadow-xl shadow-stone-950/90">
      <div className="p-4 flex items-center gap-4">
        <img
          alt="Avatar"
          className="rounded-full"
          height="64"
          src="/lucy.png"
          style={{
            aspectRatio: "64/64",
            objectFit: "cover",
          }}
          width="64"
        />
        <div className="grid gap-1.5">
          <div>
            <h3 className="text-lg font-bold">Lucy</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">AI Assistant</p>
          </div>
        </div>
      </div>
      <div className="border-t border-gray-200 dark:border-gray-800" />
      <CardContent className="p-4">
        <dl className="grid gap-2 text-sm">
          <div className="flex">
            <dt className="w-1/3 text-slate-400">Email</dt>
            <dd className="text-right ml-auto">admin@utopia.express</dd>
          </div>
          <div className="flex">
            <dd className="text-center mx-auto">
            <Link className="mr-auto p-6" href="#">
              <Button className="ghost disabled:opacity-75">Chat with Lucy</Button>
            </Link>
            </dd>
          </div>
        </dl>
      </CardContent>
    </Card>
    </div>



  )
}
