/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N5nmaMzeqlK
 */
import { Separator } from "@/components/ui/separator";

export function Coupon() {
  return (

    <div className="px-9 max-w-xl mx-auto">

      <Separator orientation="vertical" className="h-20 bg-slate-300 mx-auto"/>

      <div className="p-1 flex flex-row border border-slate-300 shadow-2xl rounded-full">
        <div className="w-1/6 pt-2 pb-2 pl-6 pr-0">
          <p className="text-right text-3xl font-normal text-slate-400">-20%</p>
        </div>
        <div className="w-3/6 pt-2 pb-2 pr-6">
          <p className="text-right text-sm font-normal text-slate-400">Use this promo code & get<br/>20% off of the first training</p>
        </div>
        <div className="w-2/6 relative pt-2 pb-2 pl-3 flex flex-row rounded-full shadow-lg shadow-fuchsia-600/30 hover:shadow-fuchsia-500/30 border-0 bg-gradient-to-br from-stone-600 to-stone-900 hover:bg-gradient-to-br hover:from-fuchsia-600 hover:to-stone-900 text-slate-200">
          <div className="text-center w-3/4 tracking-widest text-2xl font-normal text-slate-400">
            UE2024 
          </div>
          <div className="w-1/4">   
            <span className="absolute top-4 right-3 opacity-40 hover:opacity-100"><CopyIcon/></span>
          </div>
        </div>
      </div>

      <Separator orientation="vertical" className="h-32 bg-slate-300 mx-auto"/>

    </div>
  )
}


function CopyIcon() {
  return (
<svg className="float-right w-5 h-5 stroke-slate-200" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
  <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 7.5V6.108c0-1.135.845-2.098 1.976-2.192.373-.03.748-.057 1.123-.08M15.75 18H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08M15.75 18.75v-1.875a3.375 3.375 0 0 0-3.375-3.375h-1.5a1.125 1.125 0 0 1-1.125-1.125v-1.5A3.375 3.375 0 0 0 6.375 7.5H5.25m11.9-3.664A2.251 2.251 0 0 0 15 2.25h-1.5a2.251 2.251 0 0 0-2.15 1.586m5.8 0c.065.21.1.433.1.664v.75h-6V4.5c0-.231.035-.454.1-.664M6.75 7.5H4.875c-.621 0-1.125.504-1.125 1.125v12c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V16.5a9 9 0 0 0-9-9Z" />
</svg>

  )
}



