/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/a0EqUD05Il3
 */
import Link from "next/link";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { ContactCard } from "./contact-card";

export function FooterV2() {
  return (
    <footer className="w-full pb-3 pt-4">
      <div className="flex flex-col gap-2 text-center md:flex-row md:items-center md:justify-between md:gap-4 lg:gap-0 ">
        <div className="flex items-center justify-center ">
          <img
            alt="Logo"
            className="rounded-lg"
            height="32"
            src="/placeholder.svg"
            style={{
              aspectRatio: "32/32",
              objectFit: "cover",
            }}
            width="32"
          />
          <p className="text-xs font-normal text-gray-400 dark:text-gray-400">2024. Utopia Express</p>
        </div>
        <nav className="flex items-center justify-center gap-4 md:gap-6">
          <Link
            className="text-sm font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="https://clone.utopia.express/login"
          >
            Clone for boys
          </Link>
          <Link
            className="text-sm font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="https://clonegirls.utopia.express/login"
          >
            Clone for girls
          </Link>
          <Link
            className="text-sm font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="#"
          >
            Services
          </Link>


          <Link
            className="text-sm font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="#"
          >
            Contact
          </Link>

        <Dialog>
          <DialogTrigger>
          <MessageIcon/>
          </DialogTrigger>
          <DialogContent className="rounded-xl bg-transparent shadow-none border-0">
              <DialogHeader>
                <DialogTitle className="pb-9 text-slate-500">How can we help you?</DialogTitle>
                  <DialogDescription>
                        <ContactCard/>
                  </DialogDescription>
                </DialogHeader>
          </DialogContent>
        </Dialog>

        </nav>
        <div className="flex items-center justify-center space-x-4 md:space-x-8 pr-6">
          <Link className="text-gray-500 hover:text-gray-900 dark:hover:text-gray-50" href="https://www.facebook.com/www.utopia.express/">
            <FacebookIcon className="w-4 h-4" />
            <span className="sr-only">Facebook</span>
          </Link>
          <Link className="text-gray-500 hover:text-gray-900 dark:hover:text-gray-50" href="https://twitter.com/KontoTamas">
            <TwitterIcon className="w-4 h-4" />
            <span className="sr-only">Twitter</span>
          </Link>
          <Link className="text-gray-500 hover:text-gray-900 dark:hover:text-gray-50" href="https://www.linkedin.com/in/konto-tamas-70530446/">
            <LinkedinIcon className="w-4 h-4" />
            <span className="sr-only">LinkedIn</span>
          </Link>
        </div>
      </div>
    </footer>
  )
}


function FacebookIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function TwitterIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}





function LinkedinIcon() {
  return (
    <svg

      xmlns="http://www.w3.org/2000/svg"
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="currentColor"
      stroke="none"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MessageIcon() {
  return (
  <svg  width="24" height="24" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path className="fill-stone-600" d="M7.49985 0.877045C3.84216 0.877045 0.877014 3.84219 0.877014 7.49988C0.877014 11.1575 3.84216 14.1227 7.49985 14.1227C11.1575 14.1227 14.1227 11.1575 14.1227 7.49988C14.1227 3.84219 11.1575 0.877045 7.49985 0.877045ZM1.82701 7.49988C1.82701 4.36686 4.36683 1.82704 7.49985 1.82704C10.6328 1.82704 13.1727 4.36686 13.1727 7.49988C13.1727 10.6329 10.6328 13.1727 7.49985 13.1727C4.36683 13.1727 1.82701 10.6329 1.82701 7.49988ZM7.49999 9.49999C8.60456 9.49999 9.49999 8.60456 9.49999 7.49999C9.49999 6.39542 8.60456 5.49999 7.49999 5.49999C6.39542 5.49999 5.49999 6.39542 5.49999 7.49999C5.49999 8.60456 6.39542 9.49999 7.49999 9.49999Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
  )
}