/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7VFkLwBdWbx
 */
import { Separator } from "@/components/ui/separator";
import Image from "next/image";

export function HowItWorks() {
  return (
    <div className="mx-auto md:w-5/6 mt-20">

      <div className="container grid items-center gap-8 px-4 md:px-6">

        <div className="grid gap-12 md:grid-cols-2 lg:grid-cols-3 lg:gap-16">
          <div className="flex flex-col items-center gap-4">
            <div className="transition-colors	flex items-center justify-center rounded-full border bg-gray-100 hover:bg-amber-300 w-36 h-36 border-gray-200 dark:border-gray-800 dark:bg-gray-950">
              <Image
                alt="Image"
                className="object-cover pb-8"
                src="/mad.png"
                width= "337"
                height= "600"
                style={{
                  objectFit: "cover",
                }}
              />
            </div>
            <h1 className="pt-4 pb-0 pl-3 pr-3 text-slate-500 text-3xl tracking-tighter text-center">Make ads with your own face</h1>
            <p className="text-center text-xs text-stone-500 dark:text-stone-400">
            Take your business to the next level.<br/>A must have if you are an influencer or Youtuber.
            </p> 
          </div>
          <div className="flex flex-col items-center gap-4">
            <div className="transition-colors flex items-center justify-center rounded-full border bg-gray-100 hover:bg-red-600 w-36 h-36 border-gray-200 dark:border-gray-800 dark:bg-gray-950">
              <Image
                alt="Image"
                className="object-cover pb-8"
                src="/kabat.png"
                width= "337"
                height= "600"
                style={{
                  objectFit: "cover",
                }}
              />
            </div>
            <h1 className="pt-4 pb-0 pl-3 pr-3 text-slate-500 text-3xl tracking-tighter text-center">Try on a real coat virtually</h1>
            <p className="text-center text-xs text-stone-500 dark:text-stone-400">
           It's strange but it works. Your AI doesn't lie, If you can visualize your better version, 
            </p>
          </div>
          <div className="flex flex-col items-center gap-4">
            <div className="transition-colors flex items-center justify-center rounded-full border bg-slate-100 hover:bg-pink-200 w-36 h-36 border-gray-200 dark:border-gray-800 dark:bg-gray-950">
              <Image
                alt="Image"
                className="object-cover pb-8"
                src="/vv.png"
                width= "337"
                height= "600"
                style={{
                  objectFit: "cover",
                }}
              />
            </div>
            <h1 className="pt-4 pb-0 pl-3 pr-3 text-slate-500 text-3xl tracking-tighter text-center">Create hot pictures for your husband</h1>
            <p className="text-center text-xs text-stone-500 dark:text-stone-400">
            A comic where you are the main character? Or a poster series in Boris Valleyo style? The possibilities are endless.
            </p>
          </div>

        </div>
      </div>

    </div>
  )
}


function CodeIcon() {
  return (
    <svg
    className="w-8 h-8 text-gray-500 dark:text-gray-400" 
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function BuildingIcon() {
  return (
    <svg className="w-8 h-8 text-gray-500 dark:text-gray-400"
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="20" x="4" y="2" rx="2" ry="2" />
      <path d="M9 22v-4h6v4" />
      <path d="M8 6h.01" />
      <path d="M16 6h.01" />
      <path d="M12 6h.01" />
      <path d="M12 10h.01" />
      <path d="M12 14h.01" />
      <path d="M16 10h.01" />
      <path d="M16 14h.01" />
      <path d="M8 10h.01" />
      <path d="M8 14h.01" />
    </svg>
  )
}


function CommandIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path className="w-8 h-8 text-gray-500 dark:text-gray-400" d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3" />
    </svg>
  )
}


function MergeIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 6 4-4 4 4" />
      <path d="M12 2v10.3a4 4 0 0 1-1.172 2.872L4 22" />
      <path d="m20 22-5-5" />
    </svg>
  )
}
