/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7VFkLwBdWbx
 */


export function HowItWorks() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center gap-8 px-4 md:px-6">
        <div className="space-y-2 text-center">
          <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">How It Works</div>
          <h1 className="pb-4 bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text sm:text-start md:text-end text-5xl md:text-8xl font-extrabold tracking-tighter text-transparent">
            Streamline your workflow in four simple steps
          </h1>
        </div>
        <div className="grid gap-12 md:grid-cols-2 lg:grid-cols-3 lg:gap-16">
          <div className="flex flex-col items-center gap-4">
            <div className="flex items-center justify-center rounded-lg border  bg-gray-50 w-24 h-24 border-gray-200 dark:border-gray-800 dark:bg-gray-950">
              <CodeIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
            </div>
            <h3 className="text-xl font-semibold text-center">Custom Model ID</h3>
            <p className="text-center text-sm text-gray-500 md:text-base/relaxed dark:text-gray-400">
            We create a custom SDXL model for you, 
            </p>
          </div>
          <div className="flex flex-col items-center gap-4">
            <div className="flex items-center justify-center rounded-lg border border-gray-200 bg-gray-50 w-24 h-24 border-gray-200 dark:border-gray-800 dark:bg-gray-950">
              <BuildingIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
            </div>
            <h3 className="text-xl font-semibold text-center">16 Portrait Photo</h3>
            <p className="text-center text-sm text-gray-500 md:text-base/relaxed dark:text-gray-400">
            16 professional portraits in 4 different style for each training session 
            </p>
          </div>
          <div className="flex flex-col items-center gap-4">
            <div className="flex items-center justify-center rounded-lg border border-gray-200 bg-gray-50 w-24 h-24 border-gray-200 dark:border-gray-800 dark:bg-gray-950">
              <CommandIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
            </div>
            <h3 className="text-xl font-semibold text-center">50 freely generated image</h3>
            <p className="text-center text-sm text-gray-500 md:text-base/relaxed dark:text-gray-400">
            With your CloneID, you can generate any image with your Clone, in any situation.
            </p>
          </div>

        </div>
      </div>
    </section>
  )
}


function CodeIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function BuildingIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="20" x="4" y="2" rx="2" ry="2" />
      <path d="M9 22v-4h6v4" />
      <path d="M8 6h.01" />
      <path d="M16 6h.01" />
      <path d="M12 6h.01" />
      <path d="M12 10h.01" />
      <path d="M12 14h.01" />
      <path d="M16 10h.01" />
      <path d="M16 14h.01" />
      <path d="M8 10h.01" />
      <path d="M8 14h.01" />
    </svg>
  )
}


function CommandIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3" />
    </svg>
  )
}


function MergeIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 6 4-4 4 4" />
      <path d="M12 2v10.3a4 4 0 0 1-1.172 2.872L4 22" />
      <path d="m20 22-5-5" />
    </svg>
  )
}
