/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bgW8MLC9pAQ
 */
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import Image from "next/image";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { ThreeSteps } from "./three-steps";

export function Lucy() {
  return (
      <div className="mt-10 pb-10 bg-gradient-to-br from-lime-500 to-blue-500 mx-auto shadow-xl rounded-3xl border border-slate-300 md:w-2/3">

        <div className="gap-8 mx-auto">
        
          <h1 className="p-12 mt-10 animate-fade-up bg-gradient-to-br from-lime-100 to-slate-100 bg-clip-text text-start  font-extrabold tracking-tighter text-transparent drop-shadow-sm [text-wrap:balance] text-4xl md:text-5xl md:leading-[3rem]">
            <div className="relative">
              <div className="absolute">
                <span className="relative flex h-4 w-4">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-lime-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-4 w-4 bg-lime-500"></span>
                </span>
              </div>
              <Image
                alt="Image"
                className="float-left mr-8 object-cover rounded-full shadow-lg border-slate-100"
                src="/lucy2.png"
                width= "100"
                height= "100"
                style={{
                objectFit: "cover",
                }}
              />
            </div>
            Meet Lucy, Your Research Assistant
          </h1>

            <ThreeSteps/>

        
          <p className="text-2xl italic font-normal text-slate-200 text-center md:ml-8 md:mr-8 md:pl-8 md:pr-8">
                Lucy helps you refine your search, find reliable sources, 
                and interpret the information obtained. Just chat with her.
          </p> 
          <p className="text-center pt-2">
          <span className="text-blue-200 text-sm">Free for the early birds!</span>
          <Button className="h-13 m-4 bg-slate-200 border border-slate-100 hover:border-fuchsia-200 hover:bg-slate-100 shadow-fuchsia-600/10 hover:shadow-fuchsia-400/20 shadow-xl hover:shadow-xl text-stone-500 hover:text-gray-500" asChild>
              <Link href="https://search.utopia.express/" target="_blank">
                <span className="transition-all mr-3 ml-3 text-slate-500 hover:text-slate-400">Utopia Research Assistant</span>
                <span className="w-10 h-10">
                <Image
                alt="Image"
                className="float-left mr-8 object-cover rounded-full shadow-lg border-slate-100"
                src="/lucy2.png"
                width= "100"
                height= "100"
                style={{
                objectFit: "cover",
                }}
              />
                </span>
              </Link>
          </Button>
          </p>




        </div>
  


      </div>
  )
}

