/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yDVLhzuCgqy
 */
import Image from "next/image";

export function ServiceSection() {
  return (
    <section className="w-full pt-6 md:pt-12">
      <div className="container flex flex-col gap-6 px-6 md:px-10 lg:px-16 xl:px-20">
        <div className="grid gap-6 md:gap-10 items-center">
          <div className="order-2 flex items-center">
            <div className="grid gap-4 text-center md:gap-6 md:text-left">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                The Complete Platform for Building the Web
              </h2>
              <p className="text-gray-500 md:text-xl dark:text-gray-400">
                Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable.
                Open Source.
              </p>
            </div>
          </div>
          <div className="order-1">
            <Image
              alt="Hero"
              className="mx-auto aspect-[2/1] overflow-hidden rounded-lg object-cover object-center"
              height="400"
              src="/placeholder.svg"
              width="800"
            />
          </div>
        </div>
      </div>
    </section>
  )
}
