/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3E3dlWMavIx
 */
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { badgeVariants } from "@/components/ui/badge";
import Image from "next/image";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card";
import { Separator } from "@/components/ui/separator";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";




export function Tamas() {
  return (
    <div className="px-1 bg-gradient-to-br from-pink-400 to-fuchsia-500 mx-auto shadow-xl rounded-3xl border border-slate-300 sm:w-full md:w-2/3">

        <Separator orientation="vertical" className="h-16 mt-4 mb-2 bg-pink-400 mx-auto"/>   


        <div className="">
            <p className="w-full md:pt-12 text-xl font-normal text-pink-300 text-center">
              I'm a web developer who one day 
            </p>
            <p className="text-pink-100 text-3xl italic text-center drop-shadow-sm">woke up to the fact</p>
            <br/>
                <Image
                    alt="Image"
                    className="shadow-xl shadow-pink-800/60 mx-auto object-cover rounded-full border border-pink-600 bg-slate-200"
                    src="/kontotamas2.png"
                    width= "140"
                    height= "040"
                    style={{
                    objectFit: "cover",
                    }}
                />

            <p className="text-pink-100 pt-8 text-3xl italic text-center">a machine is better than me</p>
            <p className="text-xl font-normal text-pink-300 text-center">
              in so many things.
            </p> 
        </div>


        <Separator orientation="vertical" className="h-32 mt-4 mb-2 bg-pink-400 mx-auto"/>       
            <Image
                    alt="Image"
                    className="object-cover"
                    src="/car.png"
                    width= "1111"
                    height= "185"
                    style={{
                    objectFit: "cover",
                    }}
                />
          <p className="text-pink-100 text-3xl italic text-center">...existential crisis kicked in</p>
          <Separator orientation="vertical" className="h-32 mt-4 mb-2 bg-pink-400 mx-auto"/>  
    
          <p className="pt-4 text-lg font-normal text-pink-100 text-center">but I also got super excited</p>

        
          <h1 className="italic bg-gradient-to-br from-pink-100 to-pink-200 bg-clip-text text-center  font-extrabold tracking-tighter text-transparent drop-shadow-md [text-wrap:balance] text-5xl md:text-7xl md:leading-[5rem]">How does it work?</h1>

          <Separator orientation="vertical" className="h-32 mt-4 mb-6 bg-pink-400 mx-auto"/> 

          <p className="md:mx-auto text-xl font-normal text-pink-100 text-center">
          So I dig deeper and deeper down the rabbit hole
          </p>
          <p className="md:mx-auto text-8xl font-extrabold text-pink-100 text-center">
          &
          </p>

          <p className="text-pink-300 text-3xl italic text-center pb-10 mb-6">that's why I build things to make Your transition easier.</p>  

    </div>
  )
}


function OkIcon() {
  return (
<svg className="float-left mr-1 pt-1 stroke-fuchsia-200" width="13" height="13" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.49985 0.877045C3.84216 0.877045 0.877014 3.84219 0.877014 7.49988C0.877014 11.1575 3.84216 14.1227 7.49985 14.1227C11.1575 14.1227 14.1227 11.1575 14.1227 7.49988C14.1227 3.84219 11.1575 0.877045 7.49985 0.877045ZM1.82701 7.49988C1.82701 4.36686 4.36683 1.82704 7.49985 1.82704C10.6328 1.82704 13.1727 4.36686 13.1727 7.49988C13.1727 10.6329 10.6328 13.1727 7.49985 13.1727C4.36683 13.1727 1.82701 10.6329 1.82701 7.49988ZM7.49999 9.49999C8.60456 9.49999 9.49999 8.60456 9.49999 7.49999C9.49999 6.39542 8.60456 5.49999 7.49999 5.49999C6.39542 5.49999 5.49999 6.39542 5.49999 7.49999C5.49999 8.60456 6.39542 9.49999 7.49999 9.49999Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
  )
}
function EurIcon() {
  return (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-4 h-4">
    <path strokeLinecap="round" strokeLinejoin="round" d="M14.25 7.756a4.5 4.5 0 1 0 0 8.488M7.5 10.5h5.25m-5.25 3h5.25M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg>
  )
}
function MessageIcon() {
    return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-4 h-4">
        <path fillRule="evenodd" d="M12 2.25c-2.429 0-4.817.178-7.152.521C2.87 3.061 1.5 4.795 1.5 6.741v6.018c0 1.946 1.37 3.68 3.348 3.97.877.129 1.761.234 2.652.316V21a.75.75 0 0 0 1.28.53l4.184-4.183a.39.39 0 0 1 .266-.112c2.006-.05 3.982-.22 5.922-.506 1.978-.29 3.348-2.023 3.348-3.97V6.741c0-1.947-1.37-3.68-3.348-3.97A49.145 49.145 0 0 0 12 2.25ZM8.25 8.625a1.125 1.125 0 1 0 0 2.25 1.125 1.125 0 0 0 0-2.25Zm2.625 1.125a1.125 1.125 0 1 1 2.25 0 1.125 1.125 0 0 1-2.25 0Zm4.875-1.125a1.125 1.125 0 1 0 0 2.25 1.125 1.125 0 0 0 0-2.25Z" clipRule="evenodd" />
    </svg>
    )
  }


