/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bgW8MLC9pAQ
 */
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import Image from "next/image";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";

export function Toolbar() {
  return (
    <div className="mx-auto sm:w-full md:w-5/6">


      <div className="flex flex-row h-20 mt-4">
        <div className="w-1/2 border-r border-slate-300"></div>
        <div className="w-1/2"></div>
      </div>

      
      <div className="flex flex-row md:w-3/5 gap-8 mx-auto">
        <div className="w-1/5 relative py-6">
          <div className="absolute ">
            <span className="relative flex h-3 w-3">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-lime-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-3 w-3 bg-lime-500"></span>
            </span>
          </div>

          <Image
            alt="Image"
            className="object-cover rounded-full shadow-lg border-slate-100"
            src="/lucy2.png"
            width= "180"
            height= "180"
            style={{
            objectFit: "cover",
            }}
          />
        </div>
        <div className="w-4/5">
          <h1 className="text-start pb-6 animate-fade-up bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text  font-extrabold tracking-tighter text-transparent drop-shadow-sm [text-wrap:balance] text-4xl md:text-6xl md:leading-[4rem]">Free your imagination!</h1>
          <p className="text-lg text-slate-500 leading-tight">
          Your model gets better and better as you generate more and more images. Send an email to Lucy, our AI kind assistant & she will make your photos, and send it to you in minutes.
          </p>
            <Button className="border border-slate-200 bg-transparent hover:bg-transparent h-14 w-100 justify-items-stretch mt-3 transition-all tracking-wide text-sm font-normal text-slate-300 shadow-xl shadow-stone-700/10 hover:shadow-xl hover:shadow-stone-700/20 rounded-full" asChild>
                <div>
                    <Image
                        alt="Image"
                        className="object-cover rounded-full mr-2 shadow-md"
                        src="/01.png"
                        width= "34"
                        height= "34"
                        style={{
                        objectFit: "cover",
                       }}
                    />
                    <Image
                        alt="Image"
                        className="object-cover rounded-full mr-2 shadow-md"
                        src="/02.png"
                        width= "34"
                        height= "34"
                        style={{
                        objectFit: "cover",
                       }}
                    />
                    <Image
                        alt="Image"
                        className="object-cover rounded-full mr-2 shadow-md"
                        src="/04.png"
                        width= "34"
                        height= "34"
                        style={{
                        objectFit: "cover",
                       }}
                    />


                  <Dialog>
                        <DialogTrigger>
                          <Badge variant="secondary" className="text-md pl-4 pr-4 pt-1 pb-2 pulse">
                          Create a Clone
                          </Badge>
                        </DialogTrigger>
                        <DialogContent className="rounded-xl">
                          <DialogHeader>
                            <DialogTitle className="pb-9 text-slate-500">Please select your type</DialogTitle>
                            <DialogDescription>
                              <div className="flex flex-row gap-9 justify-center pb-6">
                                <div>
                                  <Link href="https://clonegirls.utopia.express/login">
                                    <Image
                                        alt="Image"
                                        className="object-cover rounded-xl shadow-xl shadow-slate-600/50 saturate-0 hover:saturate-100"
                                        src="/select-woman.png"
                                        width= "122"
                                        height= "167"
                                        style={{
                                          objectFit: "cover",
                                        }}
                                    />
                                  </Link>
                                </div>
                                <div>
                                  <Link href="https://clone.utopia.express/login">
                                    <Image
                                        alt="Image"
                                        className="object-cover rounded-xl shadow-xl shadow-slate-600/50 saturate-0 hover:saturate-100"
                                        src="/select-man.png"
                                        width= "122"
                                        height= "167"
                                        style={{
                                          objectFit: "cover",
                                        }}
                                    />
                                  </Link>
                                </div>
                              </div>
                            </DialogDescription>
                          </DialogHeader>
                        </DialogContent>
                  </Dialog>
                </div>
            </Button> 
        </div>

      </div>
    </div>
  )
}



function ArrowLeftIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      width="24"
      height="24"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth={1}
      stroke="currentColor"
      className="w-6 h-6"
    >
      <path strokeLinecap="round" strokeLinejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" />
    </svg>
  );
}

function SettingsIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      width="24"
      height="24"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth={1.5}
      stroke="currentColor"
      className="w-6 h-6"
    >
      <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 1 1-3 0m3 0a1.5 1.5 0 1 0-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m-9.75 0h9.75" />
    </svg>
  );
}


