/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3E3dlWMavIx
 */
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { badgeVariants } from "@/components/ui/badge";
import Image from "next/image";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card";
import { Separator } from "@/components/ui/separator";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";



export function Youtube() {
  return (
    <div className="text-center shadow-2xl rounded-3xl bg-gradient-to-br from-stone-950 to-stone-800">
      <h2 className="mt-8 pt-8 tracking-wide text-sm text-slate-500  transparent">Thanks for scrolling this far. Recharge yourself with:</h2>
      <h1 className="tracking-wide	mt-3 text-2xl text-slate-300  transparent">Utopia's Uplifting Songs Under</h1>
      <h1 className="bg-gradient-to-br from-stone-300 to-stone-200 bg-clip-text text-center text-8xl md:text-9xl font-extrabold tracking-tighter text-transparent ">
      3min
      </h1>

        <audio controls src="/endless.mp3" className="mx-auto mt-6 scale-80"></audio>

      
      <div className="py-6 grid md:grid-cols-6 items-center gap-6 md:gap-8">
            <Card className="mt-1 hover:mt-0 transition-all border-0 md:col-span-2 rounded-3xl shadow-xl hover:shadow-lg hover:shadow-slate-800/40 shadow-slate-800/40">
                  <Image
                    alt="Image"
                    className="rounded-2xl transition-all cover saturate-100  shadow-lg"
                    src="/hbd.jpg"
                    width= "1920"
                    height= "1080"
                    style={{
                      objectFit: "cover",
                    }}
                  />
            </Card>

            <Card className="mt-1 hover:mt-0 transition-all border-0 md:col-span-2 rounded-3xl shadow-xl hover:shadow-lg hover:shadow-slate-800/40 shadow-slate-800/40">
                  <Image
                    alt="Image"
                    className="rounded-2xl transition-all cover saturate-100  shadow-lg"
                    src="/future.jpg"
                    width= "1920"
                    height= "1080"
                    style={{
                      objectFit: "cover",
                    }}
                  />
            </Card>

            <Card className="mt-1 hover:mt-0 transition-all border-0 md:col-span-2 rounded-3xl shadow-xl hover:shadow-lg hover:shadow-slate-800/40 shadow-slate-800/40">
                  <Image
                    alt="Image"
                    className="rounded-2xl transition-all cover saturate-100  shadow-lg"
                    src="/endless.jpg"
                    width= "1920"
                    height= "1080"
                    style={{
                      objectFit: "cover",
                    }}
                  />
            </Card>
      </div>

      <div className="mx:auto">
      <p className="pt-2 text-xs text-slate-600 pb-4">Generative Music by AI with Love, Composed & Carefully Selected by Real Humans</p>
        <Button className="mb-16 mt-4 transition-all w-96 h-20 bg-stone-800 hover:bg-stone-900 border-0 shadow-xl hover:shadow-lg shadow-slate-900/100 hover:shadow-red-900/20">
          <Link href="https://www.youtube.com/channel/UCZxVdlr2Ez4xkq97fGbG3IQ">
          <span className="text-left text-lg text-bold text-red-100 mr-4">Utopia Express on Youtube</span> 
          <YoutubeIcon></YoutubeIcon>
          </Link>
        </Button>
      </div>



    </div>
  )
}

function YoutubeIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 float-right" viewBox="0 0 28.57  20" focusable="false">
  <svg viewBox="0 0 28.57 20" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg">
    <g>
      <path d="M27.9727 3.12324C27.6435 1.89323 26.6768 0.926623 25.4468 0.597366C23.2197 2.24288e-07 14.285 0 14.285 0C14.285 0 5.35042 2.24288e-07 3.12323 0.597366C1.89323 0.926623 0.926623 1.89323 0.597366 3.12324C2.24288e-07 5.35042 0 10 0 10C0 10 2.24288e-07 14.6496 0.597366 16.8768C0.926623 18.1068 1.89323 19.0734 3.12323 19.4026C5.35042 20 14.285 20 14.285 20C14.285 20 23.2197 20 25.4468 19.4026C26.6768 19.0734 27.6435 18.1068 27.9727 16.8768C28.5701 14.6496 28.5701 10 28.5701 10C28.5701 10 28.5677 5.35042 27.9727 3.12324Z" fill="#FF0000"></path>
      <path d="M11.4253 14.2854L18.8477 10.0004L11.4253 5.71533V14.2854Z" fill="white"></path>
    </g>
  </svg>
</svg>
  )
}



function ArrowLeftIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-24 h-24 text-slate-300">
  <path strokeLinecap="round" strokeLinejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
</svg>


  )
}
function EurIcon() {
  return (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-4 h-4">
    <path strokeLinecap="round" strokeLinejoin="round" d="M14.25 7.756a4.5 4.5 0 1 0 0 8.488M7.5 10.5h5.25m-5.25 3h5.25M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg>
  )
}

function EmailIcon() {
    return (
<svg className="float-start w-4 h-4  mr-1" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
  <path className="stroke-stone-500" strokeLinecap="round" strokeLinejoin="round" d="M16.5 12a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0Zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 1 0-2.636 6.364M16.5 12V8.25" />
</svg>
    )
}


function LearnIcon() {
    return (
<svg className="float-start w-4 h-4 mr-1" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.75432 1.81954C7.59742 1.72682 7.4025 1.72682 7.24559 1.81954L1.74559 5.06954C1.59336 5.15949 1.49996 5.32317 1.49996 5.5C1.49996 5.67683 1.59336 5.84051 1.74559 5.93046L7.24559 9.18046C7.4025 9.27318 7.59742 9.27318 7.75432 9.18046L13.2543 5.93046C13.4066 5.84051 13.5 5.67683 13.5 5.5C13.5 5.32317 13.4066 5.15949 13.2543 5.06954L7.75432 1.81954ZM7.49996 8.16923L2.9828 5.5L7.49996 2.83077L12.0171 5.5L7.49996 8.16923ZM2.25432 8.31954C2.01658 8.17906 1.70998 8.2579 1.56949 8.49564C1.42901 8.73337 1.50785 9.03998 1.74559 9.18046L7.24559 12.4305C7.4025 12.5232 7.59742 12.5232 7.75432 12.4305L13.2543 9.18046C13.4921 9.03998 13.5709 8.73337 13.4304 8.49564C13.2899 8.2579 12.9833 8.17906 12.7456 8.31954L7.49996 11.4192L2.25432 8.31954Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>

    )
}

function HeartIcon() {
    return (
<svg className="float-start w-4 h-4 mr-1" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4.89346 2.35248C3.49195 2.35248 2.35248 3.49359 2.35248 4.90532C2.35248 6.38164 3.20954 7.9168 4.37255 9.33522C5.39396 10.581 6.59464 11.6702 7.50002 12.4778C8.4054 11.6702 9.60608 10.581 10.6275 9.33522C11.7905 7.9168 12.6476 6.38164 12.6476 4.90532C12.6476 3.49359 11.5081 2.35248 10.1066 2.35248C9.27059 2.35248 8.81894 2.64323 8.5397 2.95843C8.27877 3.25295 8.14623 3.58566 8.02501 3.88993C8.00391 3.9429 7.98315 3.99501 7.96211 4.04591C7.88482 4.23294 7.7024 4.35494 7.50002 4.35494C7.29765 4.35494 7.11523 4.23295 7.03793 4.04592C7.01689 3.99501 6.99612 3.94289 6.97502 3.8899C6.8538 3.58564 6.72126 3.25294 6.46034 2.95843C6.18109 2.64323 5.72945 2.35248 4.89346 2.35248ZM1.35248 4.90532C1.35248 2.94498 2.936 1.35248 4.89346 1.35248C6.0084 1.35248 6.73504 1.76049 7.20884 2.2953C7.32062 2.42147 7.41686 2.55382 7.50002 2.68545C7.58318 2.55382 7.67941 2.42147 7.79119 2.2953C8.265 1.76049 8.99164 1.35248 10.1066 1.35248C12.064 1.35248 13.6476 2.94498 13.6476 4.90532C13.6476 6.74041 12.6013 8.50508 11.4008 9.96927C10.2636 11.3562 8.92194 12.5508 8.00601 13.3664C7.94645 13.4194 7.88869 13.4709 7.83291 13.5206C7.64324 13.6899 7.3568 13.6899 7.16713 13.5206C7.11135 13.4709 7.05359 13.4194 6.99403 13.3664C6.0781 12.5508 4.73641 11.3562 3.59926 9.96927C2.39872 8.50508 1.35248 6.74041 1.35248 4.90532Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>

    )
}




